src/Controllers/ArrangementResultController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SBA.Algorithm;
using SBA.DataModels;
using System.Collections.Generic;

namespace SBA.Controllers
{
    [Authorize]
    public class ArrangementResultController : Controller
    {
        public ArrangementResultController(bssContext context)
        {
        }

        public IActionResult ArrangeBox(List<int> orderIds)
        {
            var orderArr = new OrderArrangement();
            var result = orderArr.GetResult(orderIds);
            return View("Index", result);
        }

        public IActionResult GetResultByOrderResult(int orderId, int logisticId)
        {
            var obj = new OrderArrangement();
            var result = obj.GetResultByOrderResult(orderId, logisticId);
            return Json(result);
        }
    }
}

src/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SBA.DataModels;
using SBA.Repositories;
using System;

namespace SBA.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly OrderRepository _orderRepo;

        public OrderController(bssContext context)
        {
            _orderRepo = new OrderRepository(context);
        }

        public IActionResult Index()
        {
            var result = _orderRepo.GetAllOrders();
            return View(result);
        }

        public IActionResult AddOrder()
        {
            var obj = new Orders();
            obj.Date = DateTime.Now;
            return View("AddOrder", obj);
        }

        public IActionResult GetOrderByOrderNumber(string ordersnumber)
        {
            var obj = _orderRepo.GetOrderByOrderNumber(ordersnumber);
            if (obj != null)
            {
                return View("AddOrder", obj);
            }
            else
            {
                return View("AddOrder", new Orders() { Date = DateTime.Now, OrdersNumber = ordersnumber });
            }
        }

        public IActionResult GetOrderById(int id)
        {
            var obj = _orderRepo.GetOrderById(id);
            if (obj == null)
            {
                return AddOrder();
            }
            else
            {
                return View("AddOrder", obj);
            }
        }

        public IActionResult UpsertOrder(Orders obj)
        {
            var result = false;
            var method = "";

            if (obj.OrdersId > 0)
            {
                result = _orderRepo.EditOrder(obj);
                method = "Update Order";
            }
            else
            {
                result = _orderRepo.AddOrder(obj);
                method = "Add Order";
            }
            var resultMessage = result ? "Success" : "Fail";
            TempData["ActionResult"] = result;
            TempData["ActionResultMessage"] = $"{method} {resultMessage} ";
            return GetOrderById(obj.OrdersId);
        }

        public IActionResult UpsertOrderDetail(Ordersdetail obj)
        {
            var result = false;
            var method = "";

            if (obj.OrdersdetailId > 0)
            {
                result = _orderRepo.EditOrderDetail(obj);
                method = "Update OrderDetail";
            }
            else
            {
                result = _orderRepo.AddOrderDetail(obj);
                method = "Add OrderDetail ";
            }
            var resultMessage = result ? "Success" : "Fail";
            TempData["ActionResult"] = result;
            TempData["ActionResultMessage"] = $"{method} {resultMessage} ";
            return GetOrderById(obj.OrdersId);
        }

        public IActionResult DeleteOrder(int ordersid)
        {
            var result = false;
            var method = "Delete Order";

            if (ordersid > 0)
            {
                result = _orderRepo.DeleteOrder(ordersid);
            }

            var resultMessage = result ? "Success" : "Fail";
            TempData["ActionResult"] = result;
            TempData["ActionResultMessage"] = $"{method} {resultMessage} ";
            return AddOrder();
        }

        public IActionResult DeleteOrderdetail(int ordersid, int ordersdetailid)
        {
            var result = false;
            var method = "Delete Orderdetail";

            if (ordersdetailid > 0)
            {
                result = _orderRepo.DeleteOrderdetail(ordersdetailid);
            }

            var resultMessage = result ? "Success" : "Fail";
            TempData["ActionResult"] = result;
            TempData["ActionResultMessage"] = $"{method} {resultMessage} ";
            return GetOrderById(ordersid);
        }
    }
}

src/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SBA.DataModels;
using SBA.Repositories;

namespace SBA.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly ProductRepository _productRepo;

        public ProductController(bssContext context)
        {
            _productRepo = new ProductRepository(context);
        }

        public IActionResult Index()
        {
            var result = _productRepo.GetAllProduct();

            return View(result);
        }

        public IActionResult UpsertProduct(Product obj)
        {
            var result = false;
            var method = "";

            if (obj.ProductId > 0)
            {
                result = _productRepo.UpdateProduct(obj);
                method = "Update Product";
            }
            else
            {
                result = _productRepo.AddProduct(obj);
                method = "Add Product";
            }
            var resultMessage = result ? "Success" : "Fail";
            TempData["ActionResult"] = result;
            TempData["ActionResultMessage"] = $"{method} {resultMessage} ";
            return RedirectToAction("Index");
        }

        public IActionResult GetAllProduct()
        {
            return Json(new { data = _productRepo.GetAllProduct() });
        }

        public IActionResult GetProductIsArranged()
        {
            return Json(new { data = _productRepo.GetProductIsArranged() });
        }

        public IActionResult GetProductNotArranged()
        {
            return Json(new { data = _productRepo.GetProductNotArranged() });
        }
    }
}

src/Views/Order/AddOrder.cshtml
@using SBA.DataModels
@model SBA.DataModels.Orders

@{
    ViewBag.Title = "Addorder";
}

<div class="text-center">
    @if (TempData["ActionResult"] != null)
    {
        if ((bool)TempData["ActionResult"])
        {
            <div class="alert-success">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                @TempData["ActionResultMessage"]
            </div>

        }
        else
        {
            <div class="alert">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                @TempData["ActionResultMessage"]
            </div>
        }
    }
    <div class="m-panel">
        <div class="m-panel-header ">
            <h class="m-panel-name">Pick Up Order</h>
        </div>

        <div class="modal-body-left">
            <form id="form-order-item" action='@Url.Action("UpsertOrder","Order")' method="POST">
                <div class="form-group form-inline" hidden>
                    <label for="OrdersId">Order Id :  </label>
                    <input class="form-control text-center" type="text" id="OrdersId"
                           name="OrdersId" readonly placeholder="Order Id" value="@Model.OrdersId">
                </div>
                <div class="form-group form-inline">
                    <label for="OrdersNumber">Order Number :</label>
                    <input class="form-control text-center col-sm" type="text" id="OrdersNumber"
                           name="OrdersNumber" required placeholder="Order Number" value="@Model.OrdersNumber">
                    <label for="Date">Order Date :</label>
                    <input class="form-control text-center col-sm" type="date" name="Date" required
                           pattern="\d{4}-\d{2}-\d{2}" value='@Model.Date.ToString("yyyy-MM-dd")'>
                </div>
                <div class="form-group form-inline">
                    <label for="CustomerName">Customer Name :  </label>
                    <input class="form-control text-center col-sm" type="text" id="CustomerName"
                           name="CustomerName" required placeholder="Customer Name" value="@Model.CustomerName">
                </div>
                <div class="form-group form-inline">
                    <label for="CustomerAddress">Customer Address :  </label>
                    <input class="form-control text-center col-sm" pattern="[\w\s/]*[ก-๙.\s\w/-()]*[ก-๙.\s]+\d{5}" type="text" id="CustomerAddress"
                           name="CustomerAddress" 
                           required placeholder="Customer Address with zipcode" 
                           value="@Model.CustomerAddress"
                            data-toggle="tooltip" title="ex. 12 ม.12 ถ.พหลโยธิน แขวงลาดยาว เขตจตุจักร กรุงเทพ 10240">        
                </div>
            </form>
        </div>
    </div>
    <br>
    <div class="m-panel-footer">
        <button id="btn-neworder" class="btn btn-primary">New </button>
        <button class="btn btn-primary" type="submit" form="form-order-item">Save</button>
        <button id="btn-deleteorder" class="btn btn-default">Delete</button>
    </div>
</div>

<br>
<br>
@if (Model.OrdersId > 0)
{
    <div class="text-center">
        <div class="m-panel">
            <div class="m-panel-header ">
                <h class="m-panel-name">Pick Up Order Detail</h>
                <label id="txt-totalproduct" class="text-center">Total Quantity @Model.TotalProductQty Packages</label>
                <button id="btn-neworderdetail" class="btn pull-right" data-toggle='modal' data-target='#modal-orderdetail-item'>New</button>
            </div>
            <table id="table-orderdetail" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <td hidden>OrdersId</td>
                        <td hidden>OrdersdetailId</td>
                        <td>No.</td>
                        <td hidden>ProductId</td>
                        <td>Product Name</td>
                        <td>Quantity(Packages)</td>
                        <td></td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    @for (var i = 0; i < Model.OrdersDetails.Count(); i++)
                    {
                        <tr>
                            <td hidden>@Model.OrdersDetails[i].OrdersId</td>
                            <td hidden>@Model.OrdersDetails[i].OrdersdetailId</td>
                            <td>@(i + 1)</td>
                            <td hidden>@Model.OrdersDetails[i].ProductId</td>
                            <td>@Model.OrdersDetails[i].ProductName</td>
                            <td>@Model.OrdersDetails[i].Qty</td>
                            <td><a class="btn-edit">Edit</a></td>
                            <td><a class="btn-delete">Delete</a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}

<!--Add Order Detail-->
<div class="modal " id="modal-orderdetail-item" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title text-center">Pick Up Order Detail</h2>
                <button type="button" class="close" onclick="closeModalOrderDetail()" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body-left">
                <form id="form-orderdetail-item" action='@Url.Action("UpsertOrderDetail","Order")' method="POST">
                    <div class="form-group  " hidden>
                        <label for="OrdersId">Order Id :</label>
                        <input type="text" class="form-control text-center" id="modal-OrdersId" name="OrdersId">
                    </div>
                    <div class="form-group  " hidden>
                        <label for="OrdersdetailId">OrderDetail Id :</label>
                        <input type="text" class="form-control text-center" id="OrdersdetailId" name="OrdersdetailId">
                    </div>
                    <div class="form-group ">
                        <label for="ProductId">Product Name:</label>
                        <select class="form-control text-center" id="ProductId" name="ProductId" required></select>
                    </div>
                    <div class="form-group">
                        <label for="Qty">Quantity (Packages):</label>
                        <input class="form-control text-center " type="text" pattern="^[0-9]+" id="Qty" name="Qty" required placeholder="Product Quantity">
                    </div>
                </form>
            </div>
            <br>
            <div class="modal-footer">
                <button class="btn btn-default" type="button" onclick="closeModalOrderDetail()">Cancel</button>
                <button class="btn btn-primary" type="submit" form="form-orderdetail-item">Save</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
//@* set variable *@
     _tb_orderdetail = $("#table-orderdetail");
     datatable_orderdetail = null;
     _modal_orderdetail_item = $("#modal-orderdetail-item");
     _product = null;

//@* main *@
        $(document).ready(function () {
            datatable_orderdetail = _tb_orderdetail.DataTable({
                "ordering": false,
                "searching": false,
                "lengthChange": false,
                "paging": false,
                "info": false,
                destroy: true,
            });
        });
//@* bind event *@
        $("#btn-neworderdetail").on('click', function () {
            SetUnselectOrderDetailRow();
        });
        $("#btn-deleteorder").on('click', function () {
            DeleteOrder($('#OrdersId').val());
        });
        _tb_orderdetail.on('click', 'a.btn-edit', function () {
            SetSelectOrderDetailRow($(this).parent().parent());
            _modal_orderdetail_item.modal("show");
        });
        _tb_orderdetail.on('click', 'a.btn-delete', function () {
            SetSelectOrderDetailRow($(this).parent().parent());
            selectdata = datatable_orderdetail.row('.selected').data();
            DeleteOrderDetail(selectdata[0], selectdata[1]);
        });
        _modal_orderdetail_item.on("shown.bs.modal", function () {
            var data = datatable_orderdetail.row(".selected").data();
            if (data == undefined) {
                var data = [($('#OrdersId').val()), ($('#OrdersdetailId').val()), 0, null, null, null];
            }
            BindingOrderDetailSelectData(data);
        });
        $('#OrdersNumber').on('keypress', function (key) {
            if (key.key == "Enter") {
                location.replace('@Url.Action("GetOrderByOrderNumber","Order")' + "?ordersnumber=" + $(this).val());
            }
        });
        $('#btn-neworder').on('click', function () {
            location.replace('@Url.Action("AddOrder","Order")');
        });

// @* load Data  *@
        $.ajax({
            url: '@Url.Action("GetProductIsArranged","Product")',
            type: "GET",
            dataSrc: "data"
        }).done(function (data) {
            _product = data.data;
            MapSelectProduct();
        });
        
//@* function *@
        function MapSelectProduct() {
            select = $('select#ProductId');
            $.each(_product, function (k, v) {
                var $option = $("<option></option>", {
                    "text": v.name,
                    "value": v.productId
                });
                select.append($option);
            });
        };
        function closeModalOrderDetail() {
            _modal_orderdetail_item.modal("hide");
        };
        function SetUnselectOrderDetailRow() {
            _tb_orderdetail.find("tr.selected").each(function () {
                $(this).removeClass('selected');
            });
        };
        function SetSelectOrderDetailRow(row) {
            _tb_orderdetail.find("tr.selected").each(function () {
                $(this).removeClass('selected');
            });
            row.addClass('selected');
        };
        function BindingOrderDetailSelectData(data) {
            _modal_orderdetail_item.find("#modal-OrdersId")[0].value = data[0];
            _modal_orderdetail_item.find("#OrdersdetailId")[0].value = data[1];
            $("select#ProductId").val(data[3]).change();
            _modal_orderdetail_item.find("#Qty")[0].value = data[5];
        };
        function DeleteOrder(id) {
            if (id > 0) {
                r = window.confirm("Do you want to delete pick up order ?")
                if (r) {
                    location.replace('@Url.Action("DeleteOrder","Order")' + "?ordersid=" + id);
                }
            }
        };
        function DeleteOrderDetail(OrdersId, ordersdetailid) {
            if (ordersdetailid > 0) {
                r = window.confirm("Do you want to delete pick up order detail ?")
                if (r) {
                    location.replace('@Url.Action("DeleteOrderDetail","Order")' + "?ordersid=" + OrdersId + "&&ordersdetailid=" + ordersdetailid);
                }
            }
        };
    </script>
}

src/Views/Order/index.cshtml
@using SBA.DataModels
@model IEnumerable<SBA.DataModels.Orders>
@{
    ViewData["Title"] = "Order";
}

<div class="text-center">
    @if (TempData["ActionResult"] != null)
    {
        if ((bool)TempData["ActionResult"])
        {
            <div class="alert-success">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                @TempData["ActionResultMessage"]
            </div>

        }
        else
        {
            <div class="alert">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                @TempData["ActionResultMessage"]
            </div>
        }
    }
    <div class="m-panel">
        <div class="m-panel-header ">
            <h class="m-panel-name">Pick Up Order</h>
            <label id="txt-totalorder" class="text-right"></label>
        </div>
        <div>
            <table id="table-order" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th><input id="checkbox-selectorder-all" type="checkbox" value="True" class='all-check' style="display:show"></th>
                        <th hidden>OrdersId</td>
                        <th class="text-center">Order Number</th>
                        <th class="text-center">Customer Name</th>
                        <th class="text-center">Total Product</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td> <input class='check' type='checkbox' value='' id='defaultCheck1'></td>
                            <td hidden>@item.OrdersId</td>
                            <td>@item.OrdersNumber</td>
                            <td>@item.CustomerName</td>
                            <td>@item.TotalProductQty</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="">
            <button class="btn btn-primary" id="btn-arrangebox" disabled>Arrange Box</button>
        </div>
    </div>
</div>
<br>

@section Scripts{
    <script>
//@* set variable *@
        _tb_order = $("#table-order");
        datatable_order = null;
        iszeroProduct = false;

//@* main *@
        $(document).ready(function () {
            datatable_order = _tb_order.DataTable({
                "ordering": false,
                "searching": false,
                "lengthChange": false,
                "paging": false,
                "info": false,
                destroy: true,
            });
            $("#txt-totalorder").text("Total " + datatable_order.rows().count() + " Orders ");
        });

//@* bind event *@
        $("#btn-arrangebox").on('click', function () {
            var param = getOrderData();
            if (iszeroProduct) {
                alert("มี order ที่ไม่มีสินค้า กรุณาเลือกรายการอีกครั้ง?");
                    return;
            }
            paramstring = getParameterOrderIdsString(param);
            window.location.href = '@Url.Action("ArrangeBox","ArrangementResult")' + "?" + paramstring;
        });
        $("#checkbox-selectorder-all").on('click', function () {
            $(".check").prop('checked', $(this).prop('checked'));
            if ($(this).prop('checked')) {
                $(".check").each(function () {
                    setSelectOrderRow($(this).parent().parent());
                });
            }
            else {
                $(".check").each(function () {
                    setUnSelectOrderRow($(this).parent().parent());
                });
            }
        });
        $(".check").on('click', function () {
            if ($(this).prop('checked')) {
                setSelectOrderRow($(this).parent().parent());
            }
            else {
                setUnSelectOrderRow($(this).parent().parent());
            }
            if($(".check:checked").length>0){
                $("#btn-arrangebox").prop("disabled",false);
            }
            else{
                 $("#btn-arrangebox").prop("disabled",true);
            }
        });

//@* function *@
        function setSelectOrderRow(row) {
            row.addClass('selected');
        };
        function setUnSelectOrderRow(row) {
            row.removeClass('selected');
        };
        function getOrderData() {
            var data = datatable_order.rows(".selected").data();
            var result = [];
            iszeroProduct = false;
            $.each(data, function (k, d) {
                if (parseInt(d[4]) == 0) {
                    iszeroProduct = true;
                }
                result.push(d[1]);
            });
            return result;
        };
        function getParameterOrderIdsString(param) {
            var str = "";
            $.each(param, function (i, k) { str = str + "orderIds=" + k + "&" });
            return str;
        };
    </script>
}