src/Controllers/ArrangementResultController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SBA.Algorithm;
using SBA.DataModels;
using System.Collections.Generic;

namespace SBA.Controllers
{
    [Authorize]
    public class ArrangementResultController : Controller
    {
        public ArrangementResultController(bssContext context)
        {
        }

        public IActionResult ArrangeBox(List<int> orderIds)
        {
            var orderArr = new OrderArrangement();
            var result = orderArr.GetResult(orderIds);
            return View("Index", result);
        }

        public IActionResult GetResultByOrderResult(int orderId, int logisticId)
        {
            var obj = new OrderArrangement();
            var result = obj.GetResultByOrderResult(orderId, logisticId);
            return Json(result);
        }
    }
}

src/Controllers/DocumentController.cs
using jsreport.AspNetCore;
using jsreport.Types;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SBA.Algorithm;
using SBA.DataModels;
using SBA.Repositories;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace SBA.Controllers
{
    [Authorize]
    public class DocumentController : Controller
    {
        private readonly MasterRepository _masterRepo;
        private readonly OrderRepository _orderRepo;

        public DocumentController(bssContext _context)
        {
            _orderRepo = new OrderRepository(_context);
            _masterRepo = new MasterRepository(_context);
        }

        public IActionResult OrderProductNotArranged()
        {
            return View("OrderProductNotArranged", new Orders());
        }

        public IActionResult GetOrderByOrderNumber(string ordersnumber)
        {
            var obj = _orderRepo.GetOrderAllByOrderNumber(ordersnumber);
            if (obj == null)
            {
                return View("OrderProductNotArranged", new Orders() { OrdersNumber = ordersnumber });
            }
            else
            {
                return View("OrderProductNotArranged", obj);
            }
        }
        public IActionResult GetOrderDetailsList()
        {
            var obj = new List<Ordersdetail>();
            return Json(new { data = obj });
        }
        [MiddlewareFilter(typeof(JsReportPipeline))]
        public IActionResult ShippingAddressReport(int orderId)
        {
            HttpContext.JsReportFeature()
                       .Configure((req) => { if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) { req.Options.Base = "http://bss2-nginx"; } })
                       .Recipe(Recipe.ChromePdf);
            return View("ShippingAddressReport", _masterRepo.GetShippingAddress(orderId));
        }

        [MiddlewareFilter(typeof(JsReportPipeline))]
        public IActionResult ArrangementResultReport(int orderId, int logisticId)
        {
            HttpContext.JsReportFeature()
                       .Configure((req) => { if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) { req.Options.Base = "http://bss2.test"; } })
                       .Recipe(Recipe.ChromePdf);
            return View("ArrangementResultReport", (new OrderArrangement()).GetArrangementResultReport(orderId, logisticId));
        }

        [MiddlewareFilter(typeof(JsReportPipeline))]
        public IActionResult CoverBoxReport(int orderId, int logisticId)
        {
            HttpContext.JsReportFeature()
                       .Configure((req) => { if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) { req.Options.Base = "http://bss2.test"; } })
                       .Recipe(Recipe.ChromePdf);
            return View("CoverBoxReport", (new OrderArrangement()).GetCoverBoxReport(orderId, logisticId));
        }

        [MiddlewareFilter(typeof(JsReportPipeline))]
        public IActionResult CoverBoxReportNotArranged(Orders order)
        {
            HttpContext.JsReportFeature()
                       .Configure((req) => { if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) { req.Options.Base = "http://bss2.test"; } })
                       .Recipe(Recipe.ChromePdf);
            return View("CoverBoxReportNotArranged", order);
        }
    }
}

src/Views/ArrangementResult/Index.cshtml
@model SBA.Algorithm.Batch

@{
    ViewData["Title"] = "ArrangementResult";
}

<div class="text-center">
    @if (TempData["ActionResult"] != null)
    {
        if ((bool)TempData["ActionResult"])
        {
            <div class="alert-success">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                @TempData["ActionResultMessage"]
            </div>

        }
        else
        {
            <div class="alert">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                @TempData["ActionResultMessage"]
            </div>
        }
    }

    @* arrangement panel *@
    <div class="m-panel">
        <div class="m-panel-header ">
            <h class="m-panel-name">Arrangement Result</h>
        </div>
        <div class="modal-body-left">
            <form id="form-arrangement-result">
                <input hidden id="logisticid" value="@Model.LogisticId">
                <div class="form-group form-inline">
                    <label for="logisticName">Logistic Name : </label>
                    <input class="form-control text-center txt-primary txt-bold" type="text" id="logisticName"
                           name="logisticName" readonly value="@Model.LogisticName">
                    <label for="totalPrice">TotalPrice :</label>
                    <input class="form-control text-center txt-primary txt-bold" type="text" id="totalPrice"
                           name="totalPrice" required value="@Model.TotalPrice">
                    <label>baht</label>
                </div>
            </form>
        </div>
    </div>
</div>
<br>
@* orderresult panel *@
<div class="m-panel">
    <div class="m-panel-header ">
        <h class="m-panel-name">Pick Up Order Result</h>
        <label id="txt-totalorderresult" class="text-right">Total @Model.Order.Count() Orders</label>
    </div>
    <table id="table-orderresult" class="table table-striped text-center" style="width:100%">
        <thead>
            <tr>
                <th hidden></th>
                <th>Order Number</th>
                <th>Customer Name</th>
                <th>Total Product</th>
                <th>Total Box</th>
            </tr>
        </thead>
        @* Show Data *@
        <tbody>
            @for (var i = 0; i < Model.Order.Count(); i++)
            {
                <tr>
                    <td hidden>@Model.Order[i].Id</td>
                    <td>@Model.Order[i].OrderNumber</td>
                    <td>@Model.Order[i].CustomerName</td>
                    <td>@Model.Order[i].TotalBlocks</td>
                    <td>@Model.Order[i].ResultBoxes.Count()</td>
                </tr>
            }
        </tbody>
    </table>
</div>

<br>
@* order item panel *@
@for (var i = 0; i < Model.Order.Count(); i++)
{
    <div id="div_orderresult_@Model.Order[i].Id" hidden>
        <div class="m-panel">
            <div class="m-panel-header ">
                <h class="m-panel-name">Order Number : <span><a id="panel-txt-order-number">@Model.Order[i].OrderNumber</a></span></h>
                <label class="text-right">Total Box @Model.Order[i].ResultBoxes.Count() Boxes</label>
            </div>
            <table class="table table-striped text-center" style="width:100%">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Box Name</th>
                        <th>Total Weight</th>
                        <th>Total Package</th>
                        <th>Total Layer</th>
                    </tr>
                </thead>
                @* Show Data *@
                <tbody>
                    @for (var j = 0; j < Model.Order[i].ResultBoxes.Count(); j++)
                    {
                        <tr>
                            <td>@(j + 1)</td>
                            <td>@Model.Order[i].ResultBoxes[j].BoxName</td>
                            <td>@Model.Order[i].ResultBoxes[j].CurrentWeight</td>
                            <td>@Model.Order[i].ResultBoxes[j].totalBlock</td>
                            <td>@Model.Order[i].ResultBoxes[j].totalLayer</td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="m-panel-footer">
                <button id="btn-print-arrangementrpt" class="btn btn-lightdark" style="float:right" onclick="printArrangementResultReport()">พิมพ์เอกสารการจัดวาง</button>
                <button id="btn-print-coverboxrpt" class="btn btn-lightdark" style="float:right" onclick="printCoverBoxReport()">พิมพ์ใบปะหน้ากล่อง</button>
                <button id="btn-print-shippingaddressrpt" class="btn btn-lightdark" style="float:right" onclick="printShippingAddressReport()">พิมพ์ที่อยู่จัดส่ง</button>
            </div>
        </div>

        <br>
        @* order item panel *@
        @for (var j = 0; j < Model.Order[i].ResultBoxes.Count(); j++)
        {

            <div class="m-panel bg-lighterdark">
                <div class="m-panel-header ">
                    <h class="m-panel-name">Order Number : @Model.Order[i].OrderNumber BoxNo : @(j + 1) BoxName : @Model.Order[i].ResultBoxes[j].BoxName </h>
                    <label class="text-right">Total Layer @Model.Order[i].ResultBoxes[j].layers.Count() Layers</label>
                </div>
                <div>
                    @for (var k = 0; k < Model.Order[i].ResultBoxes[j].layers.Count(); k++)
                    {
                        <div class="m-panel-result col-sm-offset-1">
                            <div class="m-panel-header">
                                <h> Box: No.@(j + 1)  @Model.Order[i].ResultBoxes[j].BoxName Layer: @(k + 1)</h>
                                <label class="text-right">Total  @Model.Order[i].ResultBoxes[j].layers[k].blocks.Count() packages</label>
                            </div>
                            <br>
                            <img alt="Embedded Image" src="data:image/png;base64,@Model.Order[i].ResultBoxes[j].layers[k].Export()" />
                            <br>
                            <table class="table text-center " style="width:100%">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Product Name</th>
                                        <th>Position Flip Up</th>
                                    </tr>
                                </thead>
                                @* Show Data *@
                                <tbody>
                                    @foreach (var item in Model.Order[i].ResultBoxes[j].layers[k].blocks.GroupBy(p => p.ProductId).Select(x => x.First()).Where(p => p.ProductId != 0).OrderBy(p => p.ProductId))
                                    {
                                        <tr>
                                            <td>@item.ProductId</td>
                                            <td>@item.Name</td>
                                            <td>@item.PositionFilpup</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    }
                </div>
                <div class="m-panel-footer"></div>
            </div>
            <br>
        }
    </div>
}

@section Scripts {
    <script>

//@* set variable *@
      _tb_orderresult = $('#table-orderresult');
        datatable_orderresult = null;

//@* main *@
        $(document).ready(function () {
            datatable_orderresult = _tb_orderresult.DataTable({
                "ordering": false,
                "searching": false,
                "lengthChange": false,
                "paging": false,
                "info": false,
                destroy: true,
            });
        });

//@* bind event *@
        _tb_orderresult.on('click', 'td', function () {
            $(_tb_orderresult).find("tr").each(function () {
                setUnSelectOrderRow($(this));
            });
            setSelectOrderRow($(this).parent());
            selectdata = datatable_orderresult.row('.selected').data();
            ShowResultBox(selectdata[0]);
        });

//@* function *@
        function printArrangementResultReport() {
            var order = datatable_orderresult.row('.selected').data();
            var logisticid = $("#logisticid").val();
            if (order == undefined) return;
            getArrangementResultReport(order[0], logisticid);
        };
        function printCoverBoxReport() {
            var order = datatable_orderresult.row('.selected').data();
            var logisticid = $("#logisticid").val();
            if (order == undefined) return;
            getCoverBoxReport(order[0], logisticid);
        };
        function printShippingAddressReport() {
            var order = datatable_orderresult.row('.selected').data();
            if (order == undefined) return;
            getShippingAddressReport(order[0]);
        };
        function getCoverBoxReport(orderid, logisticid) {
            var url = '@Url.Action("CoverBoxReport","Document")' + "?" + "orderId=" + orderid + "&logisticId=" + logisticid;
            window.open(url, "_blank")
        };
        function getArrangementResultReport(orderid, logisticid) {
            var url = '@Url.Action("ArrangementResultReport","Document")' + "?" + "orderId=" + orderid + "&logisticId=" + logisticid;
            window.open(url, "_blank")
        };
        function getShippingAddressReport(orderid) {
            var url = '@Url.Action("ShippingAddressReport","Document")' + "?" + "orderId=" + orderid;
            window.open(url, "_blank")
        };
        function ShowResultBox(id) {
            $("[id^='div_orderresult']").attr('hidden', true);
            $("#div_orderresult_" + id).removeAttr('hidden');
        };
        function setSelectOrderRow(row) {
            row.addClass('selected');
        };
        function setUnSelectOrderRow(row) {
            row.removeClass('selected');
        };
    </script>

}